apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: radarr
description: radarr helm chart for Kubernetes
type: application
# image: lscr.io/linuxserver/radarr
version: 1.0.2

# image: lscr.io/linuxserver/radarr
appVersion: "5.28.0"
maintainers: []
sources:
  - https://docs.linuxserver.io/images/docker-radarr/
  - https://github.com/Radarr/Radarr
home: https://github.com/Radarr/Radarr
