apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: prowlarr
description: prowlarr helm chart for Kubernetes
type: application
version: 1.0.2

appVersion: "1.35.1"
maintainers: []
sources:
  - https://github.com/prowlarr/prowlarr
  - https://docs.linuxserver.io/images/docker-prowlarr/
home: https://github.com/prowlarr/prowlarr
